-- AlterTable
ALTER TABLE "UploadedProduct" ADD COLUMN     "pc_x_plt" DECIMAL(65,30),
ALTER COLUMN "ean_code" DROP NOT NULL,
ALTER COLUMN "weight" DROP NOT NULL,
ALTER COLUMN "m2_x_pkg" DROP NOT NULL,
ALTER COLUMN "pc_x_pkg" DROP NOT NULL,
ALTER COLUMN "m2_x_plt" DROP NOT NULL,
ALTER COLUMN "unit" DROP NOT NULL;
